/**
  ******************************************************************************
  * @file       port.h
  * @author     jake-is-ESD-protected
  * @brief      IDE port file which makes code generated by the STM32CubeIDE
  *             accessible to PIO
  ******************************************************************************
  * @attention
  * The ported code is fully contained in this files's parent folder and not 
  * changed after the fact. This file replaces the `main.h` generated by the
  * STM32CubeIDE.
  ******************************************************************************
  */

#ifndef __PORT_H
#define __PORT_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32l4xx_hal.h"
#include "main.h"

/// @brief 
/// @param  
void port_setup(void);

/// @brief 
/// @param  
void port_loop(void);

/// @brief export auto generated global variables from `main.c`
extern ADC_HandleTypeDef hadc1;
extern DMA_HandleTypeDef hdma_adc1;

extern DAC_HandleTypeDef hdac1;
extern DMA_HandleTypeDef hdma_dac_ch1;

extern SPI_HandleTypeDef hspi1;
extern SPI_HandleTypeDef hspi3;

extern TIM_HandleTypeDef htim6;


#ifdef __cplusplus
}
#endif

#endif /* __PORT_H */