/**
	******************************************************************************
	* @file       port.h
	* @author     jake-is-ESD-protected
	* @brief      IDE port file which makes code generated by the STM32CubeIDE
	*             accessible to PIO
	******************************************************************************
	* @attention
	* The ported code is fully contained in this files's parent folder and not 
	* changed after the fact. This file replaces the `main.h` generated by the
	* STM32CubeIDE.
	******************************************************************************
*/

#ifndef __PORT_H
#define __PORT_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32l4xx_hal.h"
#include "main.h"

/// @brief  Simpler user API for code before the main loop. Is always called after
///         every CubeMX function.
void port_setup(void);

/// @brief  Simpler user API for code inside the main loop. Is called on repeat in
///         the `while(1)` loop of the CubeMX code in `port.c`.
void port_loop(void);

/// @brief  export auto generated global variables from `main.c` (this part is also
///         auto generated)
DAC_HandleTypeDef hdac1;
DMA_HandleTypeDef hdma_dac_ch1;

SPI_HandleTypeDef hspi1;
SPI_HandleTypeDef hspi3;

TIM_HandleTypeDef htim6;


#ifdef __cplusplus
}
#endif

#endif /* __PORT_H */
